name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        laravel: [11.*]
        phpunit: [10.*]
        stability: [prefer-lowest, prefer-stable]
    
    name: P${{ matrix.php }} - L${{ matrix.laravel }} PU${{ matrix.phpunit }} - ${{ matrix.stability }}
    
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install dependencies
      run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest
          
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
        
    - name: Install NPM dependencies
      run: | 
        npm install
        npm run build 
        
    - name: Execute tests
      run: 'vendor/bin/phpunit'
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"

